function [] = wrappingUpOpenDARun()
%% function [] = wrappingUpOpenDARun() 
% 
% Reads out the first column of each E_oda.mat file generated by openDA and 
% pastes the columns to E.mat so the rainfall runoff model can read it. 
% 
% Gets a list of all working directories. 
% Reads in the first column of each of the E_oda.mat files in these
% directories.
% Reads the original E.mat file and overwrites the first columns with the
% ones generated by openDA. 

try
  
  % Get list of the working directories.
  worklist = dir(['model',filesep,'output']);
  nl = length(worklist);
  
  odaE = [];
  j = 0;
  for i = 1:nl
    if length(worklist(i).name) > 3 && strcmp(worklist(i).name(1:4),'work')
      j = j + 1;
      temp = load(worklist(i).name,'E');
      odaE(:,j) = temp.E(:,1);
    end
  end
  
  matE = load(['..',filesep,'resources',filesep,'restart',filesep,'E.mat']);
  
  for k = 1:j
    matE.E(:,k) = odaE(:,j);
  end
  
  E = matE.E;
  save(['..',filesep,'resources',filesep,'restart',filesep,'E.mat'],'E');
  
  exit(0);
  
catch me
  exit(1);

end

