function Out = importscript(filename, startRow, endRow)
%IMPORTFILE Import numeric data from a text file as column vectors.
%   [STN1,WBAN1,YEARMODA1,TEMP1,VARNAME1,DEWP1,VARNAME2,SLP1,VARNAME3,STP1,VARNAME4,VISIB1,VARNAME6,WDSP1,VARNAME8,MXSPD1,GUST1,MAX1,MIN1,PRCP1,SNDP1,FRSHTT1]
%   = IMPORTFILE(FILENAME) Reads data from text file FILENAME for the
%   default selection.
%
%   [STN1,WBAN1,YEARMODA1,TEMP1,VARNAME1,DEWP1,VARNAME2,SLP1,VARNAME3,STP1,VARNAME4,VISIB1,VARNAME6,WDSP1,VARNAME8,MXSPD1,GUST1,MAX1,MIN1,PRCP1,SNDP1,FRSHTT1]
%   = IMPORTFILE(FILENAME, STARTROW, ENDROW) Reads data from rows STARTROW
%   through ENDROW of text file FILENAME.
%
% Example:
%   [STN1,WBAN1,YEARMODA1,TEMP1,VarName1,DEWP1,VarName2,SLP1,VarName3,STP1,VarName4,VISIB1,VarName6,WDSP1,VarName8,MXSPD1,GUST1,MAX1,MIN1,PRCP1,SNDP1,FRSHTT1]
%   = importfile('637890-99999-2012.op',2, 293);
%
%    See also TEXTSCAN.

% Auto-generated by MATLAB on 2012/11/16 09:28:31
% Adapted by Lucas Beck, 2012/11/16



%% Initialize variables.
if nargin<=2
    startRow = 2;
    endRow = inf;
end

%% Read columns of data as strings:
% For more information, see the TEXTSCAN documentation.
formatSpec = '%6s%6s%10s%8s%3s%8s%3s%8s%3s%8s%3s%7s%3s%7s%3s%7s%7s%9s%8s%7s%6s%s%[^\n\r]';

%% Open the text file.
fileID = fopen(filename,'r');

%% Read columns of data according to format string.
% This call is based on the structure of the file used to generate this
% code. If an error occurs for a different file, try regenerating the code
% from the Import Tool.
dataArray = textscan(fileID, formatSpec, endRow(1)-startRow(1)+1, 'Delimiter', '', 'WhiteSpace', '', 'HeaderLines', startRow(1)-1, 'ReturnOnError', false);
for block=2:length(startRow)
    frewind(fileID);
    dataArrayBlock = textscan(fileID, formatSpec, endRow(block)-startRow(block)+1, 'Delimiter', '', 'WhiteSpace', '', 'HeaderLines', startRow(block)-1, 'ReturnOnError', false);
    for col=1:length(dataArray)
        dataArray{col} = [dataArray{col};dataArrayBlock{col}];
    end
end

%% Close the text file.
fclose(fileID);

%% Convert the contents of columns containing numeric strings to numbers.
% Replace non-numeric strings with NaN.
raw = repmat({''},length(dataArray{1}),length(dataArray));
for col=1:length(dataArray)-1
    raw(1:length(dataArray{col}),col) = dataArray{col};
end
numericData = NaN(size(dataArray{1},1),size(dataArray,2));

for col=[1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22]
    % Converts strings in the input cell array to numbers. Replaced non-numeric
    % strings with NaN.
    rawData = dataArray{col};
    for row=1:size(rawData, 1);
        % Create a regular expression to detect and remove non-numeric prefixes and
        % suffixes.
        regexstr = '(?<prefix>.*?)(?<numbers>([-]*(\d+[\,]*)+[\.]{0,1}\d*[eEdD]{0,1}[-+]*\d*[i]{0,1})|([-]*(\d+[\,]*)*[\.]{1,1}\d+[eEdD]{0,1}[-+]*\d*[i]{0,1}))(?<suffix>.*)';
        try
            result = regexp(rawData{row}, regexstr, 'names');
            numbers = result.numbers;
            
            % Detected commas in non-thousand locations.
            invalidThousandsSeparator = false;
            if any(numbers==',');
                thousandsRegExp = '^\d+?(\,\d{3})*\.{0,1}\d*$';
                if isempty(regexp(thousandsRegExp, ',', 'once'));
                    numbers = NaN;
                    invalidThousandsSeparator = true;
                end
            end
            % Convert numeric strings to numbers.
            if ~invalidThousandsSeparator;
                numbers = textscan(strrep(numbers, ',', ''), '%f');
                numericData(row, col) = numbers{1};
                raw{row, col} = numbers{1};
            end
        catch me
        end
    end
end


%% Allocate imported array to column variable names
 Out.STN = cell2mat(raw(:, 1));
% WBAN = cell2mat(raw(:, 2));
 Out.YEARMODA = cell2mat(raw(:, 3));
 Out.TEMP = cell2mat(raw(:, 4));
% VarName1 = cell2mat(raw(:, 5));
 Out.DEWP = cell2mat(raw(:, 6));
% VarName2 = cell2mat(raw(:, 7));
% SLP = cell2mat(raw(:, 8));
% VarName3 = cell2mat(raw(:, 9));
% STP = cell2mat(raw(:, 10));
% VarName4 = cell2mat(raw(:, 11));
% VISIB = cell2mat(raw(:, 12));
% VarName6 = cell2mat(raw(:, 13));
 Out.WDSP = cell2mat(raw(:, 14));
% VarName8 = cell2mat(raw(:, 15));
% MXSPD = cell2mat(raw(:, 16));
% GUST = cell2mat(raw(:, 17));
 Out.MAX = cell2mat(raw(:, 18));
 Out.MIN = cell2mat(raw(:, 19));
 Out.PRCP = cell2mat(raw(:, 20));
% SNDP = cell2mat(raw(:, 21));
Out.FRSHTT = cell2mat(raw(:, 22));
%Out = [STN,YEARMODA,TEMP,DEWP,WDSP,MAX,MIN,PRCP,FRSHTT];

